version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   resource_class: medium+
   steps:
      - run:
          command: |
           export ARCH=arm64
           export SUBARCH=arm64
           apt-get -y update && \
           apt-get -y upgrade && \
           apt-get -y install build-essential \
                              kernel-package \
                              libncurses5-dev \
                              zlib1g-dev \
                              libgl1-mesa-dev \
                              gcc-multilib \
                              g++-multilib \
                              python-dev \
                              llvm-dev \
                              flex \
                              bison \
                              gnupg \
                              gperf \
                              libssl-dev \
                              libesd-java \
                              bc \
                              zip \
                              curl \
                              libc6-dev \
                              git \
                              rsync \
                              wget \
                              libstdc++6 \
                              libxml2-dev \
                              libwxgtk3.0-gtk3-dev \
                              tofrodos
           git config --global user.name "v4lkyr"
           git config --global user.email "valkyr23@gmail.com"
           mkdir android
           cd android
           mkdir tools
           mkdir xiaomi
           cd tools
           mkdir toolchains
           cd toolchains
           git clone https://github.com/kdrag0n/proton-clang --depth=1
           cd ..
           git clone https://github.com/v4lkyr/anykernel3
           cd ../xiaomi
           git clone https://github.com/v4lkyr/whyred.git
           cd whyred
           git checkout q-oldwifi-eas
           ./proton-clang-build
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile